//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int codeUser { get; set; }
        public string nameUser { get; set; }
        public string phoneUser { get; set; }
        public string mailUser { get; set; }
        public string passwordUser { get; set; }
    }
}
